export default {
	'new': '发布',
	'cancel': '取消',
	'title-placeholder': '添加标题...',
	'cancel-new': '退出此次发布？',
	'new-failed': '发布失败，请再试一次',
	'new-success': '发布成功！',
	'garden-title': '秘密花园',
	'garden-detail': '详情',
	'garden-detail-feeling': '看完秘密， 匿名选择您此刻的心情',
	'garden-feeling': '心情',
	'garden-new-placeholder': '匿名吐露您的心事或秘密，具体人物或者事件 建议用化名...',
	'garden-title-length': '标题太短啦，不少于{0}字',
	'garden-content-length': '内容太少啦， 不少于{0}字',
	'goods': '尤物',
	'goods-hot': '热门推荐',
	'goods-new': '最新帖子',
	'goods-all': '全部专题',
	'goods-home': '专题主页',
	'goods-detail': '详情',
	'goods-join-title': '参与专题',
	'goods-hint': '关于这个专题，我想说...',
	'more': '更多'
}