export default {
	'module-guide': '攻略',
	'module-sale': '惠旅游',
	'module-note': '游记',
	'hot-scenics': '热门景点',
	'related-notes': '相关游记',
	'recommended-notes': '推荐游记',
	'latest-notes': '最新游记',
	'note-detail': '游记详情',
	'publish-note': '写游记',
	'scenic-placeholder': '请填写景点，多个以“/”隔开',
	'destination-required-error': '请选择目的地',
	'scenic-required-error': '请填写景点名称',
	'scenic-max-length-error': '景点名称不能超过 8 个字',
	'title-required-error': '请输入标题',
	'content-min-length-error': '正文不能为空，字数不能少于 10 个哦',
	'destination': '目的地',
	'scenic': '景点',
	'scenic-list': '景点列表',
	'scenic-detail': '景点详情',
	'scenic-summary': '景点概况',
	'scenic-location': '景点位置',
	'traffic': '交通',
	'open-time': '开放时间',
	'from': '起',
	'buy-now': '立即抢购',
};