export default {
	'optimmiz-merchant': '优选商家',
	'my-merchant': '我的商家',
	'all-area': '全部地区',
	'all-classify': '全部分类',

	'country': '全国',
	'all': '所有',
	'full': '全',

	'edit': '编辑',
	'sold-out': '下架',
	'is-sold-out': '已下架',

	'detail': '详情',
	'merchant-type': '商家类型',
	'merchant-addr': '商家地址',
	'contact-number': '联系电话',
	'call': '我要预约',
	'contact-merchant': '联系商家',
	'merchant-activity': '商家活动',
	'merchant-detail': '商家详情',
	'no-find-addr': '没有找到对应位置',

	'publish-merchant': '发布商家',
	'publish': "发布",
	'confirm': "确定",
	'cancel': "取消",
	"publish-success": "发布成功",
	"cancel-publish": "取消此次发布？",
	'upload-fm-img': '上传封面图',
	'enter-merchant-name': '商家名称(必填)',
	'enter-merchant-area': '所在地区(必填)',
	'enter-merchant-classify': '商家分类(必填)',
	'enter-merchant-addr': '商家地址(必填)不少于4个字',
	"enter-contact": "联系电话(必填)",
	'enter-activity-name': '活动名称 (非必填) 不少于{0}个字',
	'enter-activity-url': '活动链接 (非必填)',
	"activity-tip": "最多可添加{0}条活动",
	"remove-activity": "删除活动",
	"add-activity": "添加活动",
	"enter-merchant-detail": "输入商家详情不少于{0}个字...",

	'toast-upload': '请上传封面图',
	'toast-name': '商家名称不少于{0}个字',
	'toast-area': '请选择所在地区',
	'toast-classity': '请选择分类',
	'toast-addr': '商家地址不少于{0}个字',
	'toast-activity-info': '请输入完整活动信息',
	'toast-max-activity-num': '最多只能添加{0}条活动',
	'toast-contact': '请添加联系电话',
	'toast-comment': '商家详情不少于{0}个字',


}